version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: aloha_api_app
    container_name: aloha_api_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - aloha_api
    volumes:
      - ./uploads/:/app/aloha-api/uploads
  db:
    image: mysql:8.0
    container_name: aloha_api_db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - aloha_api
networks:
  aloha_api:
    driver: bridge
volumes:
  dbdata: 
    driver: local
